In [1]:
import numpy as np

In [4]:
def perceptron_single_step_update_origin(
        feature_vector,
        label,
        current_theta):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    # Your code here
    if label*(current_theta.dot(feature_vector)) <= 0:
        current_theta += label*feature_vector
    
    return (current_theta)
    raise NotImplementedError


In [5]:
def perceptron_origin(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    # Your code here
 
    current_theta = np.zeros(feature_matrix.shape[1])
    for t in range(T):
        for i in range(len(feature_matrix)):
            # Your code here
            current_theta= perceptron_single_step_update_origin(feature_matrix[i],labels[i],current_theta)
            print(current_theta)
            pass
    return(current_theta)
    raise NotImplementedError


In [6]:
mat = np.array([[-1,-1],[1,0],[-1,1.5]])
labels = np.array([1,-1,1])
perceptron_origin(mat,labels,4)

[-1. -1.]
[-1. -1.]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]
[-2.   0.5]


array([-2. ,  0.5])

In [7]:
mat = np.array([[1,0],[-1,1.5],[-1,-1]])
labels = np.array([-1,1,1])
perceptron_origin(mat,labels,2)

[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]


array([-1.,  0.])

In [8]:
mat = np.array([[-1,-1],[1,0],[-1,10]])
labels = np.array([1,-1,1])
perceptron_origin(mat,labels,12)

[-1. -1.]
[-1. -1.]
[-2.  9.]
[-3.  8.]
[-3.  8.]
[-3.  8.]
[-4.  7.]
[-4.  7.]
[-4.  7.]
[-5.  6.]
[-5.  6.]
[-5.  6.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]
[-6.  5.]


array([-6.,  5.])

In [9]:
mat = np.array([[1,0],[-1,10],[-1,-1]])
labels = np.array([-1,1,1])
perceptron_origin(mat,labels,9)

[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]
[-1.  0.]


array([-1.,  0.])

In [6]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    # Your code here
    if label*(current_theta.dot(feature_vector)+current_theta_0) <= 0:
        current_theta += label*feature_vector
        current_theta_0 += label
    
    return (current_theta, current_theta_0)
    raise NotImplementedError


In [4]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    # Your code here
    current_theta_0 = 0
    current_theta = np.array([-3,3])
    for t in range(T):
        for i in range(len(feature_matrix)):
            # Your code here
            current_theta, current_theta_0 = perceptron_single_step_update(feature_matrix[i],labels[i],current_theta,current_theta_0)
            print(current_theta,current_theta_0)
            pass
    return(current_theta,current_theta_0)
    raise NotImplementedError


In [17]:
mat = np.array([[-4,2],[-2,1],[-1,-1],[2,2],[1,-2]])
labels = np.array([1,1,-1,-1,-1])
perceptron(mat,labels,9)

[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1
[-3  3] -1


(array([-3,  3]), -1)

In [7]:
mat = np.array([[-1,1],[1,-1],[1,1],[2,2]])
labels = np.array([1,1,-1,-1])
perceptron(mat,labels,9)

[-3  3] 0
[-2  2] 1
[-3  1] 0
[-3  1] 0
[-3  1] 0
[-2  0] 1
[-2  0] 1
[-2  0] 1
[-2  0] 1
[-1 -1] 2
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1
[-2 -2] 1


(array([-2, -2]), 1)